In [83]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

# Part 1

In [84]:
df = pd.read_csv("hotels_data.csv")
df.head()

,Snapshot ID,Snapshot Date,Checkin Date,Days,Original Price,Discount Price,Discount Code,Available Rooms,Hotel Name,Hotel Stars
0,1,7/17/2015 0:00,8/12/2015 0:00,5,1178,1040,1,6,Best Western Plus Seaport Inn Downtown,3
1,1,7/17/2015 0:00,8/19/2015 0:00,5,1113,982,1,8,Best Western Plus Seaport Inn Downtown,3
2,1,7/17/2015 0:00,8/13/2015 0:00,5,4370,4240,1,3,The Peninsula New York,5
3,1,7/17/2015 0:00,7/26/2015 0:00,5,1739,1667,1,18,Eventi Hotel a Kimpton Hotel,4
4,1,7/17/2015 0:00,8/12/2015 0:00,5,1739,1672,1,3,Eventi Hotel a Kimpton Hotel,4

In [85]:
# 1.a
from datetime import datetime
from dateutil.parser import parse

def get_datetime(date_str):
    return datetime.strptime(date_str, '%m/%d/%Y %H:%M')

df["DayDiff"] = DataFrame([get_datetime(val) for val in df["Checkin Date"]]) - DataFrame([get_datetime(val) for val in df["Snapshot Date"]])
df.head()

,Snapshot ID,Snapshot Date,Checkin Date,Days,Original Price,Discount Price,Discount Code,Available Rooms,Hotel Name,Hotel Stars,DayDiff
0,1,7/17/2015 0:00,8/12/2015 0:00,5,1178,1040,1,6,Best Western Plus Seaport Inn Downtown,3,26 days
1,1,7/17/2015 0:00,8/19/2015 0:00,5,1113,982,1,8,Best Western Plus Seaport Inn Downtown,3,33 days
2,1,7/17/2015 0:00,8/13/2015 0:00,5,4370,4240,1,3,The Peninsula New York,5,27 days
3,1,7/17/2015 0:00,7/26/2015 0:00,5,1739,1667,1,18,Eventi Hotel a Kimpton Hotel,4,9 days
4,1,7/17/2015 0:00,8/12/2015 0:00,5,1739,1672,1,3,Eventi Hotel a Kimpton Hotel,4,26 days

In [86]:
#1.b

df["WeekDay"] = DataFrame([get_datetime(val).weekday() for val in df["Checkin Date"]])
df.head()

,Snapshot ID,Snapshot Date,Checkin Date,Days,Original Price,Discount Price,Discount Code,Available Rooms,Hotel Name,Hotel Stars,DayDiff,WeekDay
0,1,7/17/2015 0:00,8/12/2015 0:00,5,1178,1040,1,6,Best Western Plus Seaport Inn Downtown,3,26 days,2
1,1,7/17/2015 0:00,8/19/2015 0:00,5,1113,982,1,8,Best Western Plus Seaport Inn Downtown,3,33 days,2
2,1,7/17/2015 0:00,8/13/2015 0:00,5,4370,4240,1,3,The Peninsula New York,5,27 days,3
3,1,7/17/2015 0:00,7/26/2015 0:00,5,1739,1667,1,18,Eventi Hotel a Kimpton Hotel,4,9 days,6
4,1,7/17/2015 0:00,8/12/2015 0:00,5,1739,1672,1,3,Eventi Hotel a Kimpton Hotel,4,26 days,2

In [87]:
#1.c

df["DiscountDiff"] = df["Original Price"] - df["Discount Price"]
df.head()

,Snapshot ID,Snapshot Date,Checkin Date,Days,Original Price,Discount Price,Discount Code,Available Rooms,Hotel Name,Hotel Stars,DayDiff,WeekDay,DiscountDiff
0,1,7/17/2015 0:00,8/12/2015 0:00,5,1178,1040,1,6,Best Western Plus Seaport Inn Downtown,3,26 days,2,138
1,1,7/17/2015 0:00,8/19/2015 0:00,5,1113,982,1,8,Best Western Plus Seaport Inn Downtown,3,33 days,2,131
2,1,7/17/2015 0:00,8/13/2015 0:00,5,4370,4240,1,3,The Peninsula New York,5,27 days,3,130
3,1,7/17/2015 0:00,7/26/2015 0:00,5,1739,1667,1,18,Eventi Hotel a Kimpton Hotel,4,9 days,6,72
4,1,7/17/2015 0:00,8/12/2015 0:00,5,1739,1672,1,3,Eventi Hotel a Kimpton Hotel,4,26 days,2,67

In [88]:
#1.d

df["DiscountPerc"] = (df["DiscountDiff"]/df["Original Price"]) * 100
df.head()

,Snapshot ID,Snapshot Date,Checkin Date,Days,Original Price,Discount Price,Discount Code,Available Rooms,Hotel Name,Hotel Stars,DayDiff,WeekDay,DiscountDiff,DiscountPerc
0,1,7/17/2015 0:00,8/12/2015 0:00,5,1178,1040,1,6,Best Western Plus Seaport Inn Downtown,3,26 days,2,138,11.714771
1,1,7/17/2015 0:00,8/19/2015 0:00,5,1113,982,1,8,Best Western Plus Seaport Inn Downtown,3,33 days,2,131,11.769991
2,1,7/17/2015 0:00,8/13/2015 0:00,5,4370,4240,1,3,The Peninsula New York,5,27 days,3,130,2.974828
3,1,7/17/2015 0:00,7/26/2015 0:00,5,1739,1667,1,18,Eventi Hotel a Kimpton Hotel,4,9 days,6,72,4.140311
4,1,7/17/2015 0:00,8/12/2015 0:00,5,1739,1672,1,3,Eventi Hotel a Kimpton Hotel,4,26 days,2,67,3.852789

In [89]:
#Save df to csv
df.to_csv("Hotels_data_Changed.csv")

# Part 2

In [90]:
# 2.a

# dropping passed columns 
filtered_df = df.filter(["Hotel Name","DayDiff", "Checkin Date", "Snapshot Date", "WeekDay", "DiscountDiff", "Discount Code"], axis=1)
filtered_df.head()
#filtered_df.to_csv("Hotels_data_for_best_discount_code.csv")

,Hotel Name,DayDiff,Checkin Date,Snapshot Date,WeekDay,DiscountDiff,Discount Code
0,Best Western Plus Seaport Inn Downtown,26 days,8/12/2015 0:00,7/17/2015 0:00,2,138,1
1,Best Western Plus Seaport Inn Downtown,33 days,8/19/2015 0:00,7/17/2015 0:00,2,131,1
2,The Peninsula New York,27 days,8/13/2015 0:00,7/17/2015 0:00,3,130,1
3,Eventi Hotel a Kimpton Hotel,9 days,7/26/2015 0:00,7/17/2015 0:00,6,72,1
4,Eventi Hotel a Kimpton Hotel,26 days,8/12/2015 0:00,7/17/2015 0:00,2,67,1

In [ ]:
filtered_df["MaxDis"] = filtered_df.groupby(["Hotel Name","DayDiff", "Checkin Date", "Snapshot Date", "WeekDay"])["DiscountDiff"].transform('max')
#filtered_df.sort_values(by=["Hotel Name","DayDiff", "Checkin Date", "Snapshot Date", "WeekDay"],ascending=False).reset_index()

grouped_df = filtered_df[filtered_df["DiscountDiff"]==filtered_df["MaxDis"]].drop_duplicates(["Hotel Name","DayDiff", "Checkin Date", "Snapshot Date", "WeekDay"])
grouped_df.drop(labels=["MaxDis","DiscountDiff"], axis=1,inplace=True)
grouped_df.head()
grouped_df.to_csv("Hotels_data_for_best_discount_code_grouped.csv")
# Debug stuff for find the correct data 
#grouped_df.loc[(for_learn_df["Hotel Name"] == "1 Hotel Central Park") & (for_learn_df["DayDiff"] == "3 days") & (for_learn_df["Checkin Date"] == "11/14/2015 0:00") ]

In [ ]:
# 2.b
pred_df = grouped_df.copy()
pred_df.head()

In [ ]:
from sklearn.preprocessing import LabelEncoder


duplicateClass4=pred_df[pred_df['Discount Code']==4].head(0)
duplicateClass4=duplicateClass4.append(pred_df)

pred_df=duplicateClass4.copy()

pred_categorized_df=duplicateClass4.copy()

le=LabelEncoder()

# pre process - convert columns to categorial numebr instead of strings so fit will work.
pred_categorized_df["CheckinDate"]=le.fit_transform(pred_categorized_df["Checkin Date"])
pred_categorized_df["HotelName"]=le.fit_transform(pred_categorized_df["Hotel Name"])
pred_categorized_df["SnapshotDate"]=le.fit_transform(pred_categorized_df["Snapshot Date"])
pred_categorized_df["DayDiff"] = [t.days for t in pred_categorized_df["DayDiff"]] # convert timedelta to days

print(pred_categorized_df[pred_categorized_df["Discount Code"]==1])
print(pred_categorized_df[pred_categorized_df["Discount Code"]==2])
print(pred_categorized_df[pred_categorized_df["Discount Code"]==3])
print(pred_categorized_df[pred_categorized_df["Discount Code"]==4])

# remove target column "Discount Code" from data frame used for learning.
pred_categorized_df.drop(labels=["Discount Code","Checkin Date","Snapshot Date","Hotel Name"],axis=1, inplace=True)

# Normal distribution check

In [ ]:
pred_categorized_df.describe()
#we see here that mean is approxmetly the same as median (50%) so its probably distributes as noraml distribution

# Naive Bayes - All train All test

In [ ]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
print(pred_categorized_df.head(5))
print(len(pred_categorized_df))
y_pred = gnb.fit(pred_categorized_df, pred_df['Discount Code']).predict(pred_categorized_df)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(pred_df['Discount Code'], y_pred))

In [ ]:
y_pred.min(), y_pred.max(), y_pred.mean(),  y_pred.var()

# Cross Validation

In [ ]:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(pred_categorized_df, pred_df['Discount Code'], test_size=0.3,random_state=0) # 70% training and 30% test

X_train, X_test, y_train, y_test

# Naive Bayes - 0.3/0.7

In [ ]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train, y_train)

#Predict the response for test dataset
y_pred2 = gnb.predict(X_test)
y_pred2

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred2))

# metrics for fp,tp and etc

In [ ]:
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import itertools

def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()

In [ ]:
cm = confusion_matrix(y_test, y_pred2)

plt.figure()
plot_confusion_matrix(cm, classes=pred_df["Discount Code"].unique(),
                      title='Confusion matrix, without normalization')

In [ ]:
# cm.sum(axis=0) return array of size 4(=classes num), which every item is sum of predictions for class

FP = cm.sum(axis=0) - np.diag(cm)  # foreach class: sum prediction - TP
FN = cm.sum(axis=1) - np.diag(cm)  # foreach class: sum actuals - TP
TP = np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

FP = FP.astype(float)
FN = FN.astype(float)
TP = TP.astype(float)
TN = TN.astype(float)


def printRates(array, stat):
    print("%s for classes:" %stat)
    for i in range(len(array)):
        print("\tclass %d = %f" %(i+1, array[i]))
    print("")
    
printRates(FP, "FP")
printRates(FN, "FN")
printRates(TP, "TP")
printRates(TN, "TN")

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
printRates(TPR, "TPR")

# Specificity or true negative rate
TNR = TN/(TN+FP) 
printRates(TNR, "TNR")

# Precision or positive predictive value
PPV = TP/(TP+FP)
printRates(PPV, "PPV")

# Negative predictive value
NPV = TN/(TN+FN)
printRates(NPV, "NPV")

# Fall out or false positive rate
FPR = FP/(FP+TN)
printRates(FPR, "FPR")

# False negative rate
FNR = FN/(TP+FN)
printRates(FNR, "FNR")

# False discovery rate
FDR = FP/(TP+FP)
printRates(FDR, "FDR")

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
printRates(ACC, "ACC")

# Decision tree - cross validation

In [ ]:
from sklearn import tree

clf = tree.DecisionTreeClassifier()

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred3 = clf.predict(X_test)
y_pred3

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred3))

y_pred3

In [ ]:
cm = confusion_matrix(y_test, y_pred3)

plt.figure()
plot_confusion_matrix(cm, classes=pred_df["Discount Code"].unique(),
                      title='Confusion matrix, without normalization')

# FP , TP and etc...

In [ ]:
cm.sum(axis=0),np.diag(cm) ,cm.sum()

In [ ]:
# cm.sum(axis=0) return array of size 4(=classes num), which every item is sum of predictions for class

FP = cm.sum(axis=0) - np.diag(cm)  # foreach class: sum prediction - TP
FN = cm.sum(axis=1) - np.diag(cm)  # foreach class: sum actuals - TP
TP = np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

FP = FP.astype(float)
FN = FN.astype(float)
TP = TP.astype(float)
TN = TN.astype(float)


def printRates(array, stat):
    print("%s for classes:" %stat)
    for i in range(len(array)):
        print("\tclass %d = %f" %(i+1, array[i]))
    print("")
    
printRates(FP, "FP")
printRates(FN, "FN")
printRates(TP, "TP")
printRates(TN, "TN")

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
printRates(TPR, "TPR")

# Specificity or true negative rate
TNR = TN/(TN+FP) 
printRates(TNR, "TNR")

# Precision or positive predictive value
PPV = TP/(TP+FP)
printRates(PPV, "PPV")

# Negative predictive value
NPV = TN/(TN+FN)
printRates(NPV, "NPV")

# Fall out or false positive rate
FPR = FP/(FP+TN)
printRates(FPR, "FPR")

# False negative rate
FNR = FN/(TP+FN)
printRates(FNR, "FNR")

# False discovery rate
FDR = FP/(TP+FP)
printRates(FDR, "FDR")

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
printRates(ACC, "ACC")

# ROC

In [ ]:
pd.get_dummies(y_pred3)

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve,auc
from scipy import interp
%matplotlib inline

def PlotRoc(classifier_type, pred):
    fpr = dict()
    tpr = dict()
    roc_auc = dict()
    n_classes=4
    
    for i in range(n_classes):
        print(i)
        fpr[i], tpr[i], _ = roc_curve(np.array(pd.get_dummies(y_test))[:, i], np.array(pd.get_dummies(pred))[:, i])
        roc_auc[i] = auc(fpr[i], tpr[i])


    all_fpr = np.unique(np.concatenate([fpr[i] for i in range(n_classes)]))

    mean_tpr = np.zeros_like(all_fpr)
    for i in range(n_classes):
        mean_tpr += interp(all_fpr, fpr[i], tpr[i])

    mean_tpr /= n_classes

    fpr["macro"] = all_fpr
    tpr["macro"] = mean_tpr
    roc_auc["macro"] = auc(fpr["macro"], tpr["macro"])

    lw=2
    plt.figure(figsize=(8,5))
    plt.plot(fpr["macro"], tpr["macro"],
             label='macro-average ROC curve (area = {0:0.2f})'
                   ''.format(roc_auc["macro"]),
             color='green', linestyle=':', linewidth=4)

    colors = ['aqua', 'darkorange', 'cornflowerblue', 'yellow']
    for i, color in zip(range(n_classes), colors):
        plt.plot(fpr[i], tpr[i], color=color, lw=lw,
                 label='ROC curve of class {0} (area = {1:0.2f})'
                 ''.format(i, roc_auc[i]))

    plt.plot([0, 1], [0, 1], 'k--',color='red', lw=lw)
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.annotate('Random Guess',(.5,.48),color='red')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('ROC - Decision Tree')
    plt.legend(loc="lower right")
    plt.show()
    
    
#PlotRoc("Naive Bayes", y_pred2)
PlotRoc("Decision Tree", y_pred3)

In [ ]:
import seaborn as sns
sns.set_style('whitegrid')
%matplotlib inline

norma_train=X_train.copy()

norma_train["HotelName"]=pd.to_numeric(norma_train["HotelName"])
norma_train["CheckinDate"]=pd.to_numeric(norma_train["CheckinDate"])
norma_train["SnapshotDate"]=pd.to_numeric(norma_train["SnapshotDate"])

pd.scatter_matrix(norma_train,alpha=0.1,figsize=(14,8),diagonal='kde')

sns.pairplot(norma_train.dropna())
print(norma_train.describe())
#fig, ax = plt.subplots()
#norma_train.plot.kde(ax=ax, legend=False, title='Histogram: A vs. B')
#norma_train.plot.hist(density=True, ax=ax)
#ax.set_ylabel('Probability')
#ax.grid(axis='y')
#ax.set_facecolor('#d8dcd6')
#import numpy as np
#import statsmodels.api as sm
#import pylab
#sm.qqplot(norma_train, line='45')

In [ ]:
pd.get_dummies(y_pred)